spring:
  application:
    name: purchased-ticket-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    default-schema: main
    baseline-on-migrate: true
    schemas: main
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      purchased-ticket-group-id: purchased-ticket
    backoff:
      attempts: 5
    topic:
      purchased-ticket: purchased-ticket

server:
  port: 8082
