spring:
  application:
    name: business-logic-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: bl,security
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      purchased-ticket:
        name: purchased-ticket
        partitions: 1
        replication-factor: 1

server:
  port: 8081

cache:
  tickets:
    list:
      lifetime: 1h

security:
  user:
    roles:
      default: ROLE_PURCHASER
      purchaser: ROLE_PURCHASER
      admin: ROLE_ADMIN

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    lifetime: ${JWT_ACCESS_LIFETIME}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    lifetime: ${JWT_REFRESH_LIFETIME}
